from docx import Document
from io import BytesIO


def generate_course_docx(course_data: dict) -> BytesIO:
    doc = Document()
    
    # Title
    title = course_data.get('title', 'Project Roadmap')
    doc.add_heading(title, 0)
    
    # Intro
    doc.add_paragraph("Generated by SkillWeave AI")
    doc.add_paragraph(
        "This roadmap contains a curated list of videos and modules "
        "to help you master the topic."
    )

    modules = course_data.get('modules', [])
    
    for idx, mod in enumerate(modules, 1):
        # Module Header
        module_title = mod.get('module_title', 'Untitled Module')
        doc.add_heading(f"Module {idx}: {module_title}", level=1)
        
        # Description
        description = mod.get('description', '')
        if description:
            doc.add_paragraph(description)
        
        # Video Details
        video = mod.get('video')
        if video:
            doc.add_heading('Recommended Resource:', level=2)
            
            title_p = doc.add_paragraph()
            title_p.add_run("Video Title: ").bold = True
            title_p.add_run(video.get('title', 'Unknown Title'))
            
            channel_p = doc.add_paragraph()
            channel_p.add_run("Channel: ").bold = True
            channel_p.add_run(video.get('channelTitle', 'Unknown Channel'))
            
            # Duration if available
            duration = video.get('duration')
            if duration:
                minutes = int(duration) // 60
                seconds = int(duration) % 60
                duration_str = f"{minutes}:{seconds:02d}"
                dur_p = doc.add_paragraph()
                dur_p.add_run("Duration: ").bold = True
                dur_p.add_run(duration_str)

            # Link
            video_id = video.get('id')
            if video_id:
                link_url = f"https://www.youtube.com/watch?v={video_id}"
                link_p = doc.add_paragraph()
                link_p.add_run("Link: ").bold = True
                link_p.add_run(link_url)
            
            doc.add_paragraph("-" * 40)

    # Footer/Ending
    doc.add_heading("End of Roadmap", level=1)
    doc.add_paragraph("Good luck with your learning journey!")
            
    # Save to buffer
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
